/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Package.Interface;

import Package.Commun.Avion;
import Package.Sockets.Controleur;
/**
 *
 * @author Chiraze Haidar
 */
public class ControleurInterface extends javax.swing.JFrame
{
    /**
     * Creates new form ControleurInterface
     */
    
    private int NumVol;
    Controleur _VolSocket = null;
    
    public ControleurInterface() 
    {
        
        initComponents();
        this.setSize(1800, 1200);
        this.setLocationRelativeTo(null);
        _VolSocket = new Controleur (this);
        this.setTitle("Interface: Controleur");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ChangerAngleBoutton = new javax.swing.JButton();
        ChangerVitesseBoutton = new javax.swing.JButton();
        ChangerAltitudeBoutton = new javax.swing.JButton();
        AngleLabel = new javax.swing.JLabel();
        VitesseLabel = new javax.swing.JLabel();
        AltitudeLabel = new javax.swing.JLabel();
        TextFieldAngle = new javax.swing.JTextField();
        TextFieldVitesse = new javax.swing.JTextField();
        TextFieldAltitude = new javax.swing.JTextField();
        TextFieldVol = new javax.swing.JTextField();
        VolLabel = new javax.swing.JLabel();
        ScrollPane2 = new javax.swing.JScrollPane();
        TextArea = new javax.swing.JTextArea();
        filler = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        Separator1 = new javax.swing.JSeparator();
        Separator2 = new javax.swing.JSeparator();
        ScrollPane1 = new javax.swing.JScrollPane();
        ListeVol = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        ChangerAngleBoutton.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        ChangerAngleBoutton.setForeground(new java.awt.Color(0, 153, 153));
        ChangerAngleBoutton.setText("Changer Angle");
        ChangerAngleBoutton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255), null, null));
        ChangerAngleBoutton.setEnabled(false);
        ChangerAngleBoutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangerAngleBouttonActionPerformed(evt);
            }
        });

        ChangerVitesseBoutton.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        ChangerVitesseBoutton.setForeground(new java.awt.Color(0, 153, 153));
        ChangerVitesseBoutton.setText("Changer Vitesse");
        ChangerVitesseBoutton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255), null, null));
        ChangerVitesseBoutton.setEnabled(false);
        ChangerVitesseBoutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangerVitesseBouttonActionPerformed(evt);
            }
        });

        ChangerAltitudeBoutton.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        ChangerAltitudeBoutton.setForeground(new java.awt.Color(0, 153, 153));
        ChangerAltitudeBoutton.setText("Changer Altitude");
        ChangerAltitudeBoutton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255), null, null));
        ChangerAltitudeBoutton.setEnabled(false);
        ChangerAltitudeBoutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangerAltitudeBouttonActionPerformed(evt);
            }
        });

        AngleLabel.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        AngleLabel.setForeground(new java.awt.Color(0, 153, 153));
        AngleLabel.setText("Vitesse:");
        AngleLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        VitesseLabel.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        VitesseLabel.setForeground(new java.awt.Color(0, 153, 153));
        VitesseLabel.setText("Angle:");
        VitesseLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        VitesseLabel.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        AltitudeLabel.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        AltitudeLabel.setForeground(new java.awt.Color(0, 153, 153));
        AltitudeLabel.setText("Altitude:");
        AltitudeLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TextFieldAngle.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        TextFieldAngle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        TextFieldAngle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldAngleActionPerformed(evt);
            }
        });

        TextFieldVitesse.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        TextFieldVitesse.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        TextFieldVitesse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldVitesseActionPerformed(evt);
            }
        });

        TextFieldAltitude.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        TextFieldAltitude.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        TextFieldAltitude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldAltitudeActionPerformed(evt);
            }
        });

        TextFieldVol.setEditable(false);
        TextFieldVol.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        TextFieldVol.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        TextFieldVol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldVolActionPerformed(evt);
            }
        });

        VolLabel.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        VolLabel.setForeground(new java.awt.Color(0, 153, 153));
        VolLabel.setText("Num Vol:");
        VolLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TextArea.setEditable(false);
        TextArea.setColumns(21);
        TextArea.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        TextArea.setForeground(new java.awt.Color(204, 204, 255));
        TextArea.setRows(6);
        TextArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 2));
        ScrollPane2.setViewportView(TextArea);

        ListeVol.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 2));
        ListeVol.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        ListeVol.setForeground(new java.awt.Color(204, 204, 255));
        ListeVol.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ListeVol.setToolTipText(" ");
        addWindowListener (new java.awt.event.WindowAdapter ()
            {
                public void windowClosing (java.awt.event.WindowEvent evt)
                {
                    formWindowClosing (evt);
                }
            });
            ListeVol.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
                public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                    ListeVolValueChanged(evt);
                }
            });
            ScrollPane1.setViewportView(ListeVol);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(filler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(16, 16, 16))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(AltitudeLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AngleLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(VolLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(VitesseLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TextFieldVitesse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
                                        .addComponent(TextFieldAngle, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(TextFieldAltitude))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(28, 28, 28)
                                            .addComponent(ChangerAngleBoutton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(27, 27, 27)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(ChangerVitesseBoutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(ChangerAltitudeBoutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addComponent(TextFieldVol)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Separator1, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(ScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Separator2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(ScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1054, Short.MAX_VALUE))))
                    .addContainerGap())
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ChangerAngleBoutton)
                        .addComponent(VitesseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TextFieldAngle, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ChangerVitesseBoutton)
                            .addComponent(TextFieldVitesse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(AngleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextFieldAltitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ChangerAltitudeBoutton))
                        .addComponent(AltitudeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(9, 9, 9)
                    .addComponent(filler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(9, 9, 9)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TextFieldVol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(VolLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(Separator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(ScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(Separator2, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(2, 2, 2)
                    .addComponent(ScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(20, 20, 20))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void ChangerVitesseBouttonActionPerformed(java.awt.event.ActionEvent evt) 
    {
//GEN-FIRST:event_ChangerVitesseBouttonActionPerformed
    //TODO add your handling code here:
        if (_VolSocket != null) 
        {
            try 
            {
                _VolSocket.ChangementVitesse(NumVol, Integer.parseInt(TextFieldVitesse.getText()));
            }  
            catch (InterruptedException e) 
            {
                System.out.println(e);
                System.out.println (ControleurInterface.class.getName());
            }
        }                                             
    }
//GEN-LAST:event_ChangerVitesseBouttonActionPerformed

    private void ChangerAltitudeBouttonActionPerformed(java.awt.event.ActionEvent evt) 
    {
//GEN-FIRST:event_ChangerAltitudeBouttonActionPerformed
    // TODO add your handling code here:
        if (_VolSocket != null) 
        {
            try 
            {
                 _VolSocket.ChangementAltitude(NumVol, Integer.parseInt(TextFieldAltitude.getText()));
            } 
            catch (InterruptedException e) 
            {
                System.out.println(e);
                System.out.println (ControleurInterface.class.getName());
            }
        }
    }
//GEN-LAST:event_ChangerAltitudeBouttonActionPerformed

    private void TextFieldVolActionPerformed(java.awt.event.ActionEvent evt) 
    {
//GEN-FIRST:event_TextFieldVolActionPerformed
    //TODO add your handling code here:
    }
//GEN-LAST:event_TextFieldVolActionPerformed

    private void TextFieldVitesseActionPerformed(java.awt.event.ActionEvent evt) 
    {
//GEN-FIRST:event_TextFieldVitesseActionPerformed
    //TODO add your handling code here:
    }
//GEN-LAST:event_TextFieldVitesseActionPerformed

    private void TextFieldAngleActionPerformed(java.awt.event.ActionEvent evt) 
    {
//GEN-FIRST:event_TextFieldAngleActionPerformed
    //TODO add your handling code here:
    }
//GEN-LAST:event_TextFieldAngleActionPerformed

    private void TextFieldAltitudeActionPerformed(java.awt.event.ActionEvent evt) 
    {
//GEN-FIRST:event_TextFieldAltitudeActionPerformed
    //TODO add your handling code here:
    }
//GEN-LAST:event_TextFieldAltitudeActionPerformed

    private void ChangerAngleBouttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangerAngleBouttonActionPerformed
        // TODO add your handling code here:
        if (_VolSocket != null) 
        {
            try 
            {
                _VolSocket.ChangementAngle(NumVol, Integer.parseInt(TextFieldAngle.getText()));
            } 
            catch (InterruptedException e) 
            {
                System.out.println(e);
                System.out.println (ControleurInterface.class.getName());
            }
        }
    }//GEN-LAST:event_ChangerAngleBouttonActionPerformed

    private void ListeVolValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ListeVolValueChanged
       // TODO add your handling code here:
       if (_VolSocket._VolDetecte == null) 
       {
           return;
       }
       String Objet;
       Objet = ListeVol.getSelectedValue();
        
       if (Objet != null && !Objet.isEmpty()) 
       {
           String NomVol= Objet.substring(9, 14);
           Avion _Avion = null;
           for (int i = 0; i < _VolSocket._VolDetecte.size(); i++) 
           {
               if (_VolSocket._VolDetecte.get(i).GetInfo().GetNomVol().equals(NomVol)) 
               {
                   _Avion = _VolSocket._VolDetecte.get(i);
                   break;
               }
           }
           if (_Avion == null)
           {
               return;
           } 
    
           Object Angle = _Avion.GetInfo().GetAngle();
           Object Vitesse = _Avion.GetInfo().GetVitesse();
           Object Altitude = _Avion.GetInfo().GetAltitude();

           TextFieldAngle.setText(Angle.toString());
           TextFieldVitesse.setText(Vitesse.toString());
           TextFieldAltitude.setText(Altitude.toString());
            
           NumVol = _Avion.GetInfo().GetNumVol();
           TextFieldVol.setText(NomVol);
           ChangerAngleBoutton.setEnabled(true);
           ChangerVitesseBoutton.setEnabled(true);
           ChangerAltitudeBoutton.setEnabled(true);
       } 
       else 
       {
           NumVol = 0;
           TextFieldVol.setText("0");
           TextFieldAngle.setText("0");
           TextFieldVitesse.setText("0");
           TextFieldAltitude.setText("0");
            
           ChangerAngleBoutton.setEnabled(false);
           ChangerVitesseBoutton.setEnabled(false);
           ChangerAltitudeBoutton.setEnabled(false);
       }    
    }//GEN-LAST:event_ListeVolValueChanged

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if (_VolSocket != null)
        {
            _VolSocket.CloseConnexion();
        }
    }//GEN-LAST:event_formWindowClosing
    
    /**
      * @param args the command line arguments
     **/
    
                                                                                
    public static void main(String args[]) 
    {
    /* Set the Nimbus look and feel */
        
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
        
        try 
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) 
            {
                if ("Nimbus".equals(info.getName())) 
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException e) 
        {
            System.out.println(e);
            System.out.println("Java L&F: Look and Feel Exceptiom error!!!");
            System.out.println(ControleurInterface.class.getName());
        }
    //</editor-fold>
    
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {new ControleurInterface().setVisible(true);});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AltitudeLabel;
    private javax.swing.JLabel AngleLabel;
    private javax.swing.JButton ChangerAltitudeBoutton;
    private javax.swing.JButton ChangerAngleBoutton;
    private javax.swing.JButton ChangerVitesseBoutton;
    public javax.swing.JList<String> ListeVol;
    private javax.swing.JScrollPane ScrollPane1;
    private javax.swing.JScrollPane ScrollPane2;
    private javax.swing.JSeparator Separator1;
    private javax.swing.JSeparator Separator2;
    public javax.swing.JTextArea TextArea;
    private javax.swing.JTextField TextFieldAltitude;
    private javax.swing.JTextField TextFieldAngle;
    private javax.swing.JTextField TextFieldVitesse;
    private javax.swing.JTextField TextFieldVol;
    private javax.swing.JLabel VitesseLabel;
    private javax.swing.JLabel VolLabel;
    private javax.swing.Box.Filler filler;
    // End of variables declaration//GEN-END:variables
}
